version: "2"
run:
  modules-download-mode: vendor
  timeout: 5m
linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - errorlint
    - gocyclo
    - gosec
    - misspell
    - nilerr
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
  disable:
    - prealloc
  settings:
    gocyclo:
      min-complexity: 11
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    revive:
      rules:
        - name: dot-imports
          disabled: true
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: declaration of "(err|ctx)" shadows declaration at
      - linters:
          - unparam
        path: '_test\.go$'
      - linters:
          - gocyclo
        path: '_test\.go$'
      - linters:
          - gosec
        path: '_test\.go$'
        text: G101
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - dot
        - prefix(github.com/openshift/karpenter-operator)
        - prefix(github.com/openshift)
        - prefix(github.com/aws)
        - prefix(k8s.io)
        - prefix(sigs.k8s.io)
        - default
      custom-order: true
  exclusions:
    generated: lax
