//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureSecurity) DeepCopyInto(out *AzureSecurity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureSecurity.
func (in *AzureSecurity) DeepCopy() *AzureSecurity {
	if in == nil {
		return nil
	}
	out := new(AzureSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAzureNodeClass) DeepCopyInto(out *OpenShiftAzureNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAzureNodeClass.
func (in *OpenShiftAzureNodeClass) DeepCopy() *OpenShiftAzureNodeClass {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAzureNodeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftAzureNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAzureNodeClassList) DeepCopyInto(out *OpenShiftAzureNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenShiftAzureNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAzureNodeClassList.
func (in *OpenShiftAzureNodeClassList) DeepCopy() *OpenShiftAzureNodeClassList {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAzureNodeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftAzureNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAzureNodeClassSpec) DeepCopyInto(out *OpenShiftAzureNodeClassSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Kubelet.DeepCopyInto(&out.Kubelet)
	out.Security = in.Security
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAzureNodeClassSpec.
func (in *OpenShiftAzureNodeClassSpec) DeepCopy() *OpenShiftAzureNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAzureNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAzureNodeClassStatus) DeepCopyInto(out *OpenShiftAzureNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAzureNodeClassStatus.
func (in *OpenShiftAzureNodeClassStatus) DeepCopy() *OpenShiftAzureNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAzureNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}
