#!/usr/bin/env bash
# Syncs or diffs operand RBAC and CRDs from the OpenShift karpenter-provider-aws fork
# Helm chart into pkg/assets/karpenter/, pkg/assets/aws/, pkg/assets/crds/, and
# pkg/assets/azure/. Also syncs the AKSNodeClass CRD from the OpenShift
# Azure-karpenter-provider-azure fork.
#
# Downloads the chart at a pinned branch, renders it with `helm template`, then
# extracts RBAC resources with yq, stripping Helm labels.
# Core CRDs (karpenter.sh_*) go to pkg/assets/crds/; AWS CRDs (karpenter.k8s.aws_*)
# go to pkg/assets/aws/; Azure CRDs go to pkg/assets/azure/.
#
# When upstream adds new RBAC resources, this script will fail and list them.
# To handle a new resource, add an `extract KIND NAME FILE` call in the
# appropriate section (core or AWS) below, then re-run.
#
# Usage:
#   hack/manifest-diff-upstream.sh          # diff only (exit 1 if out of sync)
#   hack/manifest-diff-upstream.sh --sync   # overwrite assets from fork chart
#
# Requires: curl; helm, yq (auto-installed via `make manifest-diff-sync`)

set -euo pipefail

AWS_REPO_NAME="openshift/aws-karpenter-provider-aws"
AZURE_REPO_NAME="openshift/Azure-karpenter-provider-azure"
OPERAND_BRANCH="release-5.1"

NAMESPACE="openshift-karpenter"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CORE_DIR="${REPO_ROOT}/pkg/assets/karpenter"
AWS_DIR="${REPO_ROOT}/pkg/assets/aws"
AZURE_DIR="${REPO_ROOT}/pkg/assets/azure"
CRD_DIR="${REPO_ROOT}/pkg/assets/crds"
MODE="${1:-}"

YQ="${YQ:-yq}"
HELM="${HELM:-helm}"
for tool in curl "$YQ" "$HELM"; do
  command -v "$tool" &>/dev/null || { echo "ERROR: $tool not found" >&2; exit 1; }
done

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# --- Download & render -------------------------------------------------------
echo "==> Fetching ${AWS_REPO_NAME} @ ${OPERAND_BRANCH}..."
curl -sSL --retry 3 --retry-delay 2 "https://github.com/${AWS_REPO_NAME}/archive/refs/heads/${OPERAND_BRANCH}.tar.gz" | tar -xz -C "$tmpdir"
chart_dir=$(find "$tmpdir" -type d -name karpenter -path "*/charts/karpenter" 2>/dev/null | head -1)
[[ -n "$chart_dir" ]] || { echo "ERROR: failed to fetch chart" >&2; exit 1; }
crd_dir="${chart_dir}/crds"

echo "==> Rendering Helm chart..."
$HELM template karpenter "$chart_dir" \
  --namespace "$NAMESPACE" --skip-crds \
  --set "settings.clusterName=placeholder" \
  > "${tmpdir}/rendered.yaml"

# --- Extract resources --------------------------------------------------------
core_staging="${tmpdir}/core"
aws_staging="${tmpdir}/aws"
mkdir -p "$core_staging" "$aws_staging"

# Strip Helm-injected labels; keep functional ones like aggregate-to-admin.
strip='
  del(.metadata.labels["helm.sh/chart"]) |
  del(.metadata.labels["app.kubernetes.io/managed-by"]) |
  del(.metadata.labels["app.kubernetes.io/instance"]) |
  del(.metadata.labels["app.kubernetes.io/version"]) |
  del(.metadata.labels["app.kubernetes.io/name"]) |
  del(.metadata.annotations) |
  del(.metadata.labels | select(length == 0))
'

header="# DO NOT EDIT. Generated by hack/manifest-diff-upstream.sh from ${AWS_REPO_NAME} ${OPERAND_BRANCH}"

# extract KIND NAME FILE
# Pull exactly one document matching KIND/NAME from the rendered chart output,
# strip Helm metadata, and write it to FILE with a DO-NOT-EDIT header.
#   KIND  — Kubernetes resource kind (e.g. ClusterRole, RoleBinding)
#   NAME  — metadata.name to select from rendered chart
#   FILE  — output path to write the extracted document
extracted_names=""
extract() {
  local kind="$1" name="$2" file="$3"
  extracted_names+="${kind}/${name}"$'\n'
  local selected
  selected=$($YQ eval-all "select(.kind == \"$kind\" and .metadata.name == \"$name\")" "${tmpdir}/rendered.yaml")
  if [[ -z "$selected" ]]; then
    echo "ERROR: no document found for ${kind}/${name}" >&2
    exit 1
  fi
  printf '%s\n' "$header" > "$file"
  echo "$selected" | $YQ eval "$strip" - >> "$file"
}

echo "==> Extracting resources..."

# --- Core (cloud-agnostic, pkg/assets/karpenter/) ---
extract ClusterRole        karpenter-core  "${core_staging}/clusterrole-core.yaml"
extract ClusterRoleBinding karpenter-core  "${core_staging}/clusterrolebinding-core.yaml"
extract Role               karpenter       "${core_staging}/role.yaml"
extract RoleBinding        karpenter       "${core_staging}/role-binding.yaml"
extract Role               karpenter-dns   "${core_staging}/role-dns.yaml"
extract RoleBinding        karpenter-dns   "${core_staging}/role-binding-dns.yaml"

# Aggregate ClusterRole is CVO-managed (install/03_aggregate-clusterrole.yaml), not operator-reconciled.
# Mark it as handled so validation doesn't flag it.
extracted_names+="ClusterRole/karpenter-admin"$'\n'

# --- AWS (provider-specific, pkg/assets/aws/) ---
extract ClusterRole        karpenter "${aws_staging}/clusterrole.yaml"
extract ClusterRoleBinding karpenter "${aws_staging}/clusterrolebinding.yaml"

# --- Validate: no unhandled RBAC resources ------------------------------------
rendered_names=$($YQ eval '.kind + "/" + .metadata.name' "${tmpdir}/rendered.yaml" \
  | grep -E "^(Role|RoleBinding|ClusterRole|ClusterRoleBinding)/" | sort -u)

unhandled=$(comm -23 <(echo "$rendered_names") <(echo "$extracted_names" | sort -u))
if [[ -n "$unhandled" ]]; then
  echo "ERROR: upstream has RBAC resources not handled by this script:"
  echo "    ${unhandled//$'\n'/$'\n'    }"
  echo "  Add extract calls for them, then re-run."
  exit 1
fi

# --- Stage CRDs (AWS chart) ---------------------------------------------------
crd_staging="${tmpdir}/crds"
azure_staging="${tmpdir}/azure"
mkdir -p "$crd_staging" "$azure_staging"
for f in "${crd_dir}"/*.yaml; do
  [[ -f "$f" ]] || continue
  local_name="$(basename "$f")"
  dest="$crd_staging"
  if [[ "$local_name" == karpenter.k8s.aws_* ]]; then
    dest="$aws_staging"
  fi
  printf '%s\n' "$header" > "${dest}/${local_name}"
  cat "$f" >> "${dest}/${local_name}"
done

# --- Stage CRDs (Azure) ------------------------------------------------------
azure_header="# DO NOT EDIT. Generated by hack/manifest-diff-upstream.sh from ${AZURE_REPO_NAME} ${OPERAND_BRANCH}"
echo "==> Fetching ${AZURE_REPO_NAME} @ ${OPERAND_BRANCH}..."
curl -sSL --retry 3 --retry-delay 2 "https://github.com/${AZURE_REPO_NAME}/archive/refs/heads/${OPERAND_BRANCH}.tar.gz" | tar -xz -C "$tmpdir"
azure_crd_dir=$(find "$tmpdir" -type d -path "*/charts/karpenter/crds" -not -path "*aws*" 2>/dev/null | head -1)
[[ -n "$azure_crd_dir" ]] || { echo "ERROR: failed to find Azure chart CRDs" >&2; exit 1; }

for f in "${azure_crd_dir}"/karpenter.azure.com_*.yaml; do
  [[ -f "$f" ]] || continue
  local_name="$(basename "$f")"
  printf '%s\n' "$azure_header" > "${azure_staging}/${local_name}"
  cat "$f" >> "${azure_staging}/${local_name}"
done

# --- Diff or sync -------------------------------------------------------------
# diff_dir EXPECTED ACTUAL [GLOB] [STRICT]
# Compare expected (upstream) files against actual (local) directory.
# Reports MISSING (expected has it, actual doesn't) and DIFF (content mismatch).
# In strict mode, also reports EXTRA (actual has it, expected doesn't).
# Returns non-zero on drift.
#   EXPECTED — directory with the reference files (e.g. freshly rendered from upstream)
#   ACTUAL   — local directory to compare against
#   GLOB     — shell glob restricting the EXTRA check in ACTUAL (default: *.yaml)
#   STRICT   — "true" (default) to flag EXTRA files in ACTUAL; "false" for one-way compare
diff_dir() {
  local expected="$1" actual="$2" glob="${3:-*.yaml}" strict="${4:-true}"
  local label="${actual#"${REPO_ROOT}"/}"
  local rc=0
  for f in "${expected}"/*.yaml; do
    [[ -f "$f" ]] || continue
    local base actual_file
    base=$(basename "$f")
    actual_file="${actual}/${base}"
    if [[ ! -f "$actual_file" ]]; then
      echo "MISSING: ${label}/${base}"; rc=1; continue
    fi
    local norm_up="${tmpdir}/u-${base}" norm_lo="${tmpdir}/l-${base}"
    grep -v '^[[:space:]]*#' "$f"           | $YQ eval '.' - > "$norm_up" 2>/dev/null || true
    grep -v '^[[:space:]]*#' "$actual_file" | $YQ eval '.' - > "$norm_lo" 2>/dev/null || true
    if ! diff -q "$norm_up" "$norm_lo" &>/dev/null; then
      echo "DIFF: ${label}/${base}"
      diff -u "$norm_up" "$norm_lo" --label "upstream/${base}" --label "local/${base}" || true
      rc=1
    fi
  done
  if [[ "$strict" == "true" ]]; then
    for f in "${actual}"/${glob}; do
      [[ -f "$f" ]] || continue
      [[ -f "${expected}/$(basename "$f")" ]] || { echo "EXTRA: ${label}/$(basename "$f")"; rc=1; }
    done
  fi
  return $rc
}

if [[ "$MODE" == "--sync" ]]; then
  rm -f "${CORE_DIR}"/*.yaml
  cp "${core_staging}"/*.yaml "${CORE_DIR}/"
  rm -f "${AWS_DIR}"/*.yaml
  cp "${aws_staging}"/*.yaml "${AWS_DIR}/"
  mkdir -p "$CRD_DIR" "$AZURE_DIR"
  rm -f "${CRD_DIR}"/*.yaml
  cp "${crd_staging}"/*.yaml "${CRD_DIR}/"
  rm -f "${AZURE_DIR}"/*.yaml
  cp "${azure_staging}"/*.yaml "${AZURE_DIR}/"
  echo "==> Synced. Review:"
  echo "      git diff pkg/assets/"
  exit 0
fi

echo "==> Comparing..."
exitcode=0
diff_dir "$core_staging" "$CORE_DIR" || exitcode=1
diff_dir "$aws_staging" "$AWS_DIR" || exitcode=1
diff_dir "$crd_staging" "$CRD_DIR" || exitcode=1
diff_dir "$azure_staging" "$AZURE_DIR" || exitcode=1

if [[ $exitcode -eq 0 ]]; then
  echo "==> In sync with ${AWS_REPO_NAME} ${OPERAND_BRANCH}."
else
  echo "==> OUT OF SYNC. Run: hack/manifest-diff-upstream.sh --sync"
fi
exit $exitcode
